# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-12 03:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('peerhelp', '0002_auto_20181111_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerVotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_votes', models.PositiveIntegerField(default=0)),
                ('down_votes', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionVotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_votes', models.PositiveIntegerField(default=0)),
                ('down_votes', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='down_votes',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='up_votes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='down_votes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='up_votes',
        ),
        migrations.AddField(
            model_name='questionvotes',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peerhelp.Question'),
        ),
        migrations.AddField(
            model_name='questionvotes',
            name='voter_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answervotes',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peerhelp.Answer'),
        ),
        migrations.AddField(
            model_name='answervotes',
            name='voter_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
