# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-12 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerhelp', '0005_auto_20181112_0331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answervotes',
            name='down_votes',
        ),
        migrations.RemoveField(
            model_name='answervotes',
            name='up_votes',
        ),
        migrations.RemoveField(
            model_name='questionvotes',
            name='down_votes',
        ),
        migrations.RemoveField(
            model_name='questionvotes',
            name='up_votes',
        ),
        migrations.AddField(
            model_name='answer',
            name='down_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='up_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answervotes',
            name='down_vote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answervotes',
            name='up_vote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='down_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='up_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionvotes',
            name='down_vote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionvotes',
            name='up_vote',
            field=models.BooleanField(default=False),
        ),
    ]
