# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-22 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[(b'admin', b'admin'), (b'auditor', b'auditor'), (b'mentor', b'mentor'), (b'task_updater', b'task_updater'), (b'worker', b'worker')], default=b'worker', max_length=15),
        ),
    ]
