# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-28 00:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181022_2047'),
        ('users', '0002_auto_20181022_2131'),
    ]

    operations = [
    ]
