# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-28 22:58
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_20181028_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='audit_prob_user',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0299999999999999988897769753748434595763683319091796875'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fine',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0200000000000000004163336342344337026588618755340576171875'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.05000000000000000277555756156289135105907917022705078125'), max_digits=10),
        ),
    ]
