# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-03 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0002_auto_20181127_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastmessages',
            name='br_params',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
