# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_desc', models.CharField(max_length=500)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
