# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-20 05:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchtasks',
            name='worker_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='worker_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
