# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-20 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20181020_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchtasks',
            name='answer',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='researchtasks',
            name='claim_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
