# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-20 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20181020_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchtasks',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='researchtasks',
            name='confidence_level',
            field=models.IntegerField(blank=True, choices=[(1, b'poor'), (2, b'below average'), (3, b'average'), (4, b'above average'), (5, b'good'), (6, b'average')], null=True),
        ),
        migrations.AddField(
            model_name='researchtasks',
            name='submission_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
