# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-20 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20181020_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchtasks',
            name='confidence_level',
            field=models.IntegerField(blank=True, choices=[(1, b'poor'), (2, b'below average'), (3, b'average'), (4, b'above average'), (5, b'good')], null=True),
        ),
    ]
