# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-20 17:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0006_auto_20181020_0602'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskUserJunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_time', models.DateTimeField(auto_now_add=True)),
                ('answer', models.CharField(blank=True, max_length=500, null=True)),
                ('submission_time', models.DateTimeField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('confidence_level', models.IntegerField(blank=True, choices=[(1, b'poor'), (2, b'below average'), (3, b'average'), (4, b'above average'), (5, b'good')], null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='researchtasks',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='researchtasks',
            name='claim_time',
        ),
        migrations.RemoveField(
            model_name='researchtasks',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='researchtasks',
            name='confidence_level',
        ),
        migrations.RemoveField(
            model_name='researchtasks',
            name='submission_time',
        ),
        migrations.RemoveField(
            model_name='researchtasks',
            name='worker_id',
        ),
        migrations.AddField(
            model_name='researchtasks',
            name='creator_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='researchtasks',
            name='num_workers',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='researchtasks',
            name='task_summary',
            field=models.CharField(default=b'Enter a single line summary', max_length=500),
        ),
        migrations.AddField(
            model_name='researchtasks',
            name='task_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='researchtasks',
            name='task_desc',
            field=models.TextField(default=b'Describe the task'),
        ),
        migrations.AddField(
            model_name='taskuserjunction',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.ResearchTasks'),
        ),
        migrations.AddField(
            model_name='taskuserjunction',
            name='worker_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
