# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-28 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20181020_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchtasks',
            name='audit_by',
            field=models.IntegerField(choices=[(1, b'Task'), (2, b'Worker')], default=2),
        ),
        migrations.AddField(
            model_name='researchtasks',
            name='audit_prob',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=2),
        ),
        migrations.AddField(
            model_name='researchtasks',
            name='bonus_task',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=4),
        ),
        migrations.AddField(
            model_name='researchtasks',
            name='fine_task',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=4),
        ),
        migrations.AddField(
            model_name='researchtasks',
            name='salary_by',
            field=models.IntegerField(choices=[(1, b'Task'), (2, b'Worker')], default=2),
        ),
        migrations.AddField(
            model_name='researchtasks',
            name='salary_task',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=4),
        ),
    ]
