# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-28 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskuserjunction',
            name='audit_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.Audit'),
        ),
        migrations.AddField(
            model_name='taskuserjunction',
            name='task_audit',
            field=models.BooleanField(default=False),
        ),
    ]
