# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-28 06:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_auto_20181028_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='auditor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
