# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-28 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_auto_20181028_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='task_correct',
            field=models.NullBooleanField(choices=[(None, b''), (True, b'Yes'), (False, b'No')], default=None, max_length=3),
        ),
    ]
