# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-28 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_auto_20181028_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchtasks',
            name='audit_prob',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=3),
        ),
        migrations.AlterField(
            model_name='researchtasks',
            name='bonus_task',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=4),
        ),
        migrations.AlterField(
            model_name='researchtasks',
            name='fine_task',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=4),
        ),
        migrations.AlterField(
            model_name='researchtasks',
            name='salary_task',
            field=models.DecimalField(decimal_places=2, default=0.02, max_digits=4),
        ),
    ]
